title: Italian Entertainment
description: Un sito per tutte le cose di Italian Entertainment
baseurl: "/"
url: "https://strainx.github.io/support"

back_to_top: true
back_to_top_text: "Torna in cima"

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

aux_links:
  "Gruppo":
    - "https://www.roblox.com/groups/16524350/Italian-Entertainment#!/about"
  "Gioco":
    - "https://www.roblox.com/games/11909019975/Italian-Universe"

color_scheme: dark

remote_theme: just-the-docs/just-the-docs
